### ISSUE TITLE
Return value if liked or disliked (for example) is null - bug or feature?

### ISSUE THREAD

**Issue by andreasba** [cybercog/laravel-love#10]
Good evening @a-komarev 

a big cnacuba for this great package, I like it ;)

I just implemented it and while I was testing it via tinker, I thought "Is this a bug or a feature?"

See examples below:

```
>>> $user->like($question)
=> null
>>> $user->unlike($question)
=> null
>>> $user->dislike($question)
=> null
>>> $user->like($question)
=> null
>>> $user->dislike($question)
=> null
```

Not sure what your view on it is, I thought that if working with the package, it would make more sense to actually return true if the action succeeded and false if it didn't, don't you think?

Thanks
Andreas

**Comment by a-komarev** [comment]
Hello @andreasba!

I'm glad you like this package.

This is inspired from [programming principle Tell-Don't-Ask](https://www.martinfowler.com/bliki/TellDontAsk.html).

If there will be error - you will know about it via Exceptions:
- `\Cog\Contracts\Love\Like\Exceptions\InvalidLikeType`
- `\Cog\Contracts\Love\Liker\Exceptions\InvalidLiker`

If there is no exception - you know that it's successfully executed.
Try to imagine the situation, why should it return `false`?

**Comment by andreasba** [comment]
Hi @a-komarev 

thanks for your quick reply :) 👍 

Ah, I did not know that princinple - I just found the behaviour different than to what I have seen so far.

Maybe mention it in the docs? :)

Anyway, thanks again, I will close the issue then, if it is okay for you.

Andreas

**Comment by a-komarev** [comment]
I rarely see this principle to be used in software development, and facing a lot of times that I don't know how to follow this design solution in some situations, but this case was pretty straightforward and clear.

You are right, it would be great to highlight it in documentation in future. And I've found that there are no `@throws` in `Liker` trait which are required.

Thank you for rasing this question!
