### ISSUE TITLE
[Question] How to make reaction faster?

### ISSUE THREAD

**Issue by vlados** [cybercog/laravel-love#104]
I love the package but the background jobs are being process after the view is being send to the frontend which makes it very strange for the user.
So if we have a website with posts. Each post have love and hate reaction. If the user clicks to add a new reaction because this reactions are processed in the background the user needs to wait few seconds which is not possible in some cases or not good.

@cybercog Can you explain how to deal with this?
The easiest way is to specify queue which to process this reactions.

**Comment by antonkomarev** [comment]
It is a good question, @vlados!

You can create the endpoint `POST /reactions` which will be responsible for reacting to the reactables.

If there is no exception raised from `reactTo` method - then you can return `201 Created` status code and instantly increment counter on the frontend. In other cases don't increment counter but display error if there is a need.

If `QUEUE_CONNECTION` is defined in `.env` file - counters & totals will be updated on background. More details about it could be found in [Aggregation Queue](https://laravel-love.readme.io/v8.0/docs/aggregation-queue) section of the documentation.

**Comment by antonkomarev** [comment]
One more possible way:
Add listener which will await for `Cog\Laravel\Love\Reaction\Events\ReactionHasBeenAdded` event and will dispatch broadcasting event via websockets. Then your users will receive changes in realtime.

And await for `Cog\Laravel\Love\Reaction\Events\ReactionHasBeenRemoved` event when you want to broadcast reaction removal.

**Comment by vlados** [comment]
Yes, so basically to fake it on the frontend until is done on the backend and with websockets to update it when is done.
I was thinking something like that but I wanted to ask if there is more cleaver way to do it

**Comment by antonkomarev** [comment]
If you will update counter on response with `2xx` status code it's not a fake really. Unless there is no exception thrown you may be sure that reaction was added or removed successfully. You just can't say that nobody else added or removed reaction between your click and getting response.

**Comment by antonkomarev** [comment]
I'm closing this issue. Feel free to continue conversation here if you'll find more optimal approach or there is anything missing in this thread.

**Comment by jtomek** [comment]
Well done, a nice implementation. 
I was wondering, how can I access the reaction data in my event handler? It's throwing the following error:
`Cannot access private property Cog\Laravel\Love\Reaction\Events\ReactionHasBeenRemoved::$reaction`

**Comment by antonkomarev** [comment]
@jtomek Have you tried `$event->getReaction()` method?

**Comment by jtomek** [comment]
So I updated from v5 to v8 today. It's brilliant from the logic perspective. But so so hard to use ... 

Do I really have to do this to get likes and dislikes from an event?

```
$interactions = [
      'likes' => $event->getReaction()->getReactant()->getReactable()->viaLoveReactant()->getReactionCounterOfType('Like')->getCount(),
      'dislikes' => $event->getReaction()->getReactant()->getReactable()->viaLoveReactant()->getReactionCounterOfType('Dislike')->getCount()
    ];
```

**Comment by antonkomarev** [comment]
Usually I'm firing broadcasting events and intercepting them on frontend to increment\decrement counters.

If you really need to have aggregated values your code could be optimized a bit:
```php
$event->getReaction()->getReactant()->getReactionCounterOfType(ReactionType::fromName('Like'))->getCount(),
```

**Comment by jtomek** [comment]
Thank you. I didn't think of intercepting single events. Maybe that's easier. I'll look into it.

I have also encountered another problem with events, can you please help?

I implemented a custom toggle logic based on your suggestion in https://github.com/cybercog/laravel-love/issues/117. 

```
$userReactrer = auth()->user()->viaLoveReacter();

if ($request->type === 'like') {

    // Remove own dislike
    if ($userReactrer->hasReactedTo($model, 'Dislike')) {
        $userReactrer->unreactTo($model, 'Dislike');
    }
    if ($userReactrer->hasReactedTo($model, 'Like')) {
        $userReactrer->unreactTo($model, 'Like');
    } else {
        $userReactrer->reactTo($model, 'Like');
    }
} else {

    // Remove own like
    if ($userReactrer->hasReactedTo($model, 'Like')) {
        $userReactrer->unreactTo($model, 'Like');
    }
    if ($userReactrer->hasReactedTo($model, 'Dislike')) {
        $userReactrer->unreactTo($model, 'Dislike');
    } else {
        $userReactrer->reactTo($model, 'Dislike');
    }
};
```

This is firing two events. Although on the background, it's working great; my problem is that it's not counting the totals in my events right. I'm getting weird numbers, sometimes it even increases the wrong reaction type.

I thought of delaying it could help, but am not sure how to implement it. Or maybe I need to be more cleaver on the frontend.

Could you please help?

**Comment by antonkomarev** [comment]
Yeah, it looks right, because counters recounting is starting on background after `ReactionHasBeenAdded` & `ReactionHasBeenRemoved` events dispatch. If you will do it instantly - it will be too "expensive" operation.

You could ignore persisted counters and compute those values manually inside of the controller, but it will work only for small projects.

If there is an ability to use broadcasting events - you'd better use them instead of relying on counters. Counters are required to quick load initial data.
