### ISSUE TITLE
love_reacter_id null

### ISSUE THREAD

**Issue by reinierkors** [cybercog/laravel-love#105]
Hi, just installed the package.

How to generate missing love_reacter_id's with existing data & db seeder?

**Comment by antonkomarev** [comment]
Hi @reinierkors!

You need to register your `Reacterable` models as `Reacter`.

The easiest way to do it:
```php
$users = User::all();

foreach ($users as $user) {
    $user->registerAsLoveReacter();
}
```

If model already registered as `Reacter` then `Cog\Contracts\Love\Reacterable\Exceptions\AlreadyRegisteredAsLoveReacter` exception will be thrown.

Same operation required to be done for `Reactable` models: Comment, Article, Post, etc.

```php
$articles = Article::all();

foreach ($articles as $article) {
    $article->registerAsLoveReactant();
}
```

If model already registered as `Reactant` then `Cog\Contracts\Love\Reactable\Exceptions\AlreadyRegisteredAsLoveReactant` exception will be thrown.

**Comment by antonkomarev** [comment]
It will be good to have artisan commands to automate this operations.

**Comment by reinierkors** [comment]
Thanks for the quick response. I see, wasn't really clear from the setup guide.

**Comment by vesper8** [comment]
It's still not very clear to me... @antonkomarev is it necessary to run

```
$users = User::all();

foreach ($users as $user) {
    $user->registerAsLoveReacter();
}

$articles = Article::all();

foreach ($articles as $article) {
    $article->registerAsLoveReactant();
}
```

If I've already set up my user model as Reacterable and my article model as Reactable as per the setup guide?

Or will this occur automatically the first time a User tries to react to an Article?

**Comment by antonkomarev** [comment]
If you integrated package after user\article was created - you need to register those models manually. All models which will be created after package integration will be registered automatically.

I plan to automate this stuff by resolving #106

**Comment by antonkomarev** [comment]
When you are registering reacterable `User` model - new record in `love_reacters` table will be created and its `id` will be set to the `users.love_reacter_id`.

When you are registering reactable `Article` model - new record in `love_reactants` table will be created and its `id` will be set to the `articles.love_reactant_id`.

**Comment by vesper8** [comment]
Ok thanks I understand now.

BTW a small distinction to make. On my user model, my primary key is not an incrementing key, that's because I share the ID of my forum as my primary key for my Laravel users table. The end result is that the ID, while numerical, is not incrementing. So what you just said `and its id will be set to the users.love_reacter_id` is not accurate.

The same is true for one of my Reactable models, it uses a string as a primary key (weird me with all my edge cases)

But anyway it seems to have worked fine. Instead of `and its id will be set to the users.love_reacter_id` what is happening is that a new sequential id is generated when the new love_reacters/love_reactants is created, and THAT id is used on the reacter/reactant model

**Comment by youssefzahar** [comment]
> Hi @reinierkors!
> 
> You need to register your `Reacterable` models as `Reacter`.
> 
> The easiest way to do it:
> 
> ```
> $users = User::all();
> 
> foreach ($users as $user) {
>     $user->registerAsLoveReacter();
> }
> ```
> 
> If model already registered as `Reacter` then `Cog\Contracts\Love\Reacterable\Exceptions\AlreadyRegisteredAsLoveReacter` exception will be thrown.
> 
> Similar operation required to be done for `Reactable` models: Comment, Article, Post, etc. But they need to be registered as `Reactant` models.
> 
> ```
> $articles = Article::all();
> 
> foreach ($articles as $article) {
>     $article->registerAsLoveReactant();
> }
> ```
> 
> If model already registered as `Reactant` then `Cog\Contracts\Love\Reactable\Exceptions\AlreadyRegisteredAsLoveReactant` exception will be thrown.
> 
> If `User` can react to other users, then `User` model should be registered as `Reacter` & `Reactant`.

hello i registred manually and i does give me Cog\Contracts\Love\Reactable\Exceptions\AlreadyRegisteredAsLoveReactant so the user is a reacter however the Reacter not exists error is still there. I tried to modify database and made love_reacter_id and love_reactant_id and made them not null with 0 as the default value but still the same error
