### ISSUE TITLE
Add Artisan commands for registering Reacter & Reactant models

### ISSUE THREAD

**Issue by antonkomarev** [cybercog/laravel-love#106]
Resolves #105

Need to add 2 Artisan commands for populating `love_reacter_id` & `love_reactant_id` columns.

#### Variant 1

```sh
love:register-reacter --model=User --ids=1,2
```

#### Variant 2

```sh
love:reacter-register --model=User --ids=1,2
```

#### Variant 3

```sh
love:register reacter --model=User --ids=1,2
```

#### Variant 4

```sh
love:reacter register --model=User --ids=1,2
```

#### Variant 5

```sh
able:register love-reacter --model=User --ids=1,2
```

#### Variant 1

```sh
love:register-reactant --model=Comment --ids=1,2
```

#### Variant 2

```sh
love:reactant-register --model=Comment --ids=1,2
```

#### Variant 3

```sh
love:register reactant --model=Comment --ids=1,2
```

#### Variant 4

```sh
love:reactant register --model=Comment --ids=1,2
```

#### Variant 5

```sh
able:register love-reactant --model=Comment --ids=1,2
```

**Comment by antonkomarev** [comment]
If `--ids` option not set - it should register all the models.

**Comment by sburkett** [comment]
@antonkomarev I'm working on this now :) I have it working, just need to clean it up a bit and put into a proper PR. I can't assign myself to the enhancement due to permissions here, but feel free to assign it to me if you'd like.

**Comment by antonkomarev** [comment]
@sburkett what command variant did you choose?

**Comment by sburkett** [comment]
```
// Specific model IDs
love:register-reactant --model=User --ids=1,2

// All model IDs
love:register-reactant --model=User
```

Same nomenclature for `Reacters` as well.

**Comment by sburkett** [comment]
### Here is the output of artisan help for the reactant command:

![image](https://user-images.githubusercontent.com/2219483/68152068-ebac2d80-ff10-11e9-8341-8c9db6d27461.png)

### Use Cases

Process all records for the passed model:
```
php artisan love:register-reactables App\\Models\\Entry
```

Process specific records for the passed model:
```
php artisan love:register-reactables App\\Models\\Entry --ids=1,2,3,4,19
```

Process all records for the passed model with a different primary key than 'id':
```
php artisan love:register-reactables App\\Models\\Entry --key='custom_primary_key'
```

### Sample output (yes, I love progress bars lol):

![image](https://user-images.githubusercontent.com/2219483/68152166-1bf3cc00-ff11-11e9-8e2f-391de3e8fa0c.png)

**Comment by antonkomarev** [comment]
Looks good for me!
I have only one question: why do we need to add `--key` option if we can determine id using `getKey` method?

**Comment by sburkett** [comment]
My thought was to avoid the overhead of another method call, especially if someone is processing a ton of model records. I agree, though, that `getKey()` is more semantically correct. Want me to change that?

**Comment by sburkett** [comment]
Of course, I could always create a temp model before processing, just to get the key. that might make more sense.

**Comment by antonkomarev** [comment]
Since its rare calls we shouldn't care about extra method calls. It will be much more developer friendly if command will foresee what to do.

**Comment by sburkett** [comment]
Also, I believe it should be `$model->getKeyName()` ... `getKey()`  returns the value of the primary key for a populated model.

**Comment by sburkett** [comment]
Ok, that part is done :D Also now reports the key, just for a little extra info.

![image](https://user-images.githubusercontent.com/2219483/68162375-e0173180-ff25-11e9-90f5-e947559bc693.png)

**Comment by sburkett** [comment]
Ok, the reacters command is finished as well. Going to do a PR request either tonight or tomorrow :)

![image](https://user-images.githubusercontent.com/2219483/68171277-1a41fc80-ff41-11e9-826b-701e05bb8e54.png)

**Comment by sburkett** [comment]
Hey @antonkomarev I need to be added to the org here with permissions to push to a PR branch, etc.

**Comment by antonkomarev** [comment]
@sburkett you can fork repository, create branch in the fork and after then you will be able to create PR to this repo from the forked repo without being the organization member.

**Comment by sburkett** [comment]
Yeah, I'll just do that. No worries :)

**Comment by antonkomarev** [comment]
@sburkett I'm not against to add you to organization. If you really want to join - its just matter of time.

**Comment by sburkett** [comment]
No worries. PR is now available :)

#127

**Comment by antonkomarev** [comment]
PR #127 merged to master. New commands will be available since v8.2

**Comment by antonkomarev** [comment]
Both commands were covered with tests. Will try to find some time to publish next version tomorrow.

**Comment by prince-vishal** [comment]
This command is not working, No matter how many times I run this. Please help
![Screenshot from 2020-05-22 10-50-51](https://user-images.githubusercontent.com/47712741/82633991-4772a580-9c1a-11ea-914d-259e7eb13c3c.png)

**Comment by antonkomarev** [comment]
@prince-vishal is your `love_reacters` table empty?

Could you show output of this command?
```sql
SELECT love_reacter_id FROM users WHERE id = 1;
```
