### ISSUE TITLE
Eager load

### ISSUE THREAD

**Issue by reinierkors** [cybercog/laravel-love#108]
Hi, what's the best way to prevent N+1 problem and eager load the vote counts?

**Comment by antonkomarev** [comment]
Hi @reinierkors!
There is [Eager Loading section in documentation](https://laravel-love.readme.io/v8.0/docs/eager-loading). If you only need to display reactions count without breakdown for an actual reacters display - you could load these relations:
```php
$comment = Comment::query()
    ->with([
        'loveReactant.reactionCounters',
        'loveReactant.reactionTotal',
    ])
    ->get();
```

You could read documentation to understand difference between [Reaction Counter](https://laravel-love.readme.io/v8.0/docs/reaction-counter) and [Reaction Total](https://laravel-love.readme.io/v8.0/docs/reaction-total)

**Comment by jayenne** [comment]
FYI: in seeders you can also use... `Model::with(['loveReacter])` & ` Model::with(['loveReactant'])`
