### ISSUE TITLE
[Question] About the use of Traits and Contracts

### ISSUE THREAD

**Issue by raniesantos** [cybercog/laravel-love#12]
The README says this:

Use `Cog\Contracts\Love\Liker\Models\Liker` contract in model which will get likes
behavior and implement it **OR** just use `Cog\Laravel\Love\Liker\Models\Traits\Liker` trait.

*(Same for Likeable.)*

Emphasis on the 'OR'.

'OR' implies that this will work even if I don't use both, so I tried to use this package with *traits only*.

I got these errors through Tinker:

![screenshot from 2018-02-17 00-26-32](https://user-images.githubusercontent.com/8528269/36317940-64ab69a6-1379-11e8-907f-2ef7b3343686.png)

If this error is intended/supposed to happen, you should change the README to say that both are needed.

**Comment by a-komarev** [comment]
Contracts are required. I wanted to say that you could implement them by yourself or just use trait if it fits your requirements out of the box.
