### ISSUE TITLE
Migration issue

### ISSUE THREAD

**Issue by sburkett** [cybercog/laravel-love#124]
I had a botched install on a new project, so I decided to start over.

Running Laravel 5.8.35, PHP 7.2.22, `"cybercog/laravel-love": "^8.1"`

### Summary of Commands Detailed Below

```
clear.sh
php artisan migrate:reset
composer remove cybercog/laravel-love
... Removed relevant lines from `User` model
clear.sh
composer require cybercog/laravel-love
php artisan migrate
php artisan love:reaction-type-add --default
php artisan migrate
php artisan love:setup-reacterable --model="App\Models\User"
php artisan migrate
```

### Detailed Command Info/Output

Ran my usual clear script:

```
#!/usr/bin/bash

composer dump

php artisan clear-compiled
php artisan auth:clear-resets
php artisan cache:clear
php artisan config:clear
php artisan event:clear
php artisan optimize:clear
php artisan route:clear
php artisan view:clear

composer dump
```

Rolled back all of the migrations.

```
$ php artisan migrate:reset
Rolling back: 2019_10_26_194331_create_sessions_table
Rolled back:  2019_10_26_194331_create_sessions_table (0.01 seconds)
Rolling back: 2018_07_25_001000_create_love_reactant_reaction_totals_table
Rolled back:  2018_07_25_001000_create_love_reactant_reaction_totals_table (0 seconds)
Rolling back: 2018_07_25_000000_create_love_reactant_reaction_counters_table
Rolled back:  2018_07_25_000000_create_love_reactant_reaction_counters_table (0 seconds)
Rolling back: 2018_07_22_002000_create_love_reactions_table
Rolled back:  2018_07_22_002000_create_love_reactions_table (0 seconds)
Rolling back: 2018_07_22_001500_create_love_reaction_types_table
Rolled back:  2018_07_22_001500_create_love_reaction_types_table (0.01 seconds)
Rolling back: 2018_07_22_001000_create_love_reactants_table
Rolled back:  2018_07_22_001000_create_love_reactants_table (0 seconds)
Rolling back: 2018_07_22_000100_create_love_reacters_table
Rolled back:  2018_07_22_000100_create_love_reacters_table (0 seconds)
```

Removed the laravel/love package - no clue about the dupe message re: `laravel/framework`, though.

```
$ composer remove cybercog/laravel-love
Dependency "laravel/framework" is also a root requirement, but is not explicitly whitelisted. Ignoring.
Dependency "laravel/framework" is also a root requirement, but is not explicitly whitelisted. Ignoring.
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 0 updates, 1 removal
  - Removing cybercog/laravel-love (8.1.2)
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: beyondcode/laravel-dump-server
Discovered Package: fideloper/proxy
Discovered Package: laravel/tinker
#!/usr/bin/bash
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Package manifest generated successfully.
```

Also removed the relevant lines from my `User` model (the `use` statements, trait, etc.).

Ran my clear script again, for good measure.

Everything looked good - no stray columns or foreign keys in my `users` table.

Ok, time to start anew!

Followed the instructions again. When I got to the step about setting up the Reacterer I ran into a problem:

```
$ php artisan love:setup-reacterable --model="App\Models\User"
Migration created successfully!
$ php artisan migrate

Migrating: 2019_11_02_124353_add_love_reacter_id_to_users_table

   Illuminate\Database\QueryException  : SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`testsite`.`#sql-62d0_1271f`, CONSTRAINT `users_love_reacter_id_foreign` FOREIGN KEY (`love_reacter_id`) REFERENCES `love_reacters` (`id`)) (SQL: alter table `users` add constraint `users_love_reacter_id_foreign` foreign key (`love_reacter_id`) references `love_reacters` (`id`))

  at /var/www/testsite/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664
    660|         // If an exception occurs when attempting to run a query, we'll format the error
    661|         // message to include the bindings with SQL, which will make this exception a
    662|         // lot more helpful to the developer instead of just the database's errors.
    663|         catch (Exception $e) {
  > 664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668| 

  Exception trace:

  1   PDOException::("SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`testsite`.`#sql-62d0_1271f`, CONSTRAINT `users_love_reacter_id_foreign` FOREIGN KEY (`love_reacter_id`) REFERENCES `love_reacters` (`id`))")
      /var/www/testsite/vendor/laravel/framework/src/Illuminate/Database/Connection.php:458

  2   PDOStatement::execute()
      /var/www/testsite/vendor/laravel/framework/src/Illuminate/Database/Connection.php:458
```

Any ideas on this one?

**Comment by sburkett** [comment]
Quick update. I truncated my `users` table, as there was only the one row in it for me. Then I removed the `love_reacter_id` that was added to that table during the botched migration above. After that, the migration ran successfully.

As a suggestion, you may want to catch exceptions in the migration(s) and revert anything done in that migration prior to the exception being thrown. Just a thought!

Once you've seen this issue here in Github and are aware of any potential issue or improvements you want to make, feel free to close it - thanks!

**Comment by sburkett** [comment]
Ok, one final update. I ran into a similar issue in setting up the Reactables. Same solution ... I exported the existing contents to a SQL file, removed the `love_reactant_id` column  that was added during the botched migration for the reactable setup. I reran the migration and it worked. So it seems that whenever there is existing data in the target tables in the setup phases, it chokes.

Even when I ran the above steps, of course it added the column again - which is fine. When I imported my SQL again, that column is set to 0 for all rows. So I'm thinking it would be beneficial to have a separate artisan command that will populate those love-related columns in the target tables to get everything in alignment.

**Comment by antonkomarev** [comment]
Yes, that issue exists for not nullable models.

This command has no issues. I faced this issue too late after release and using nullable columns in my project at this moment:
```sh
$ php artisan love:setup-reacterable --model="App\Models\User" --nullable
```

**Comment by sburkett** [comment]
Ok, I rolledback everything, and use that approach, and all went well ... until I tried to test the package. I'll file that in a separate issue. though :) Closing this out for now.

**Comment by antonkomarev** [comment]
@sburkett I really appreciate your attention and glad to receive a feedback.

I have a repository where I've tested migration between the versions. It doesn't cover all the use cases, but I've tried to collect the most usual and maybe it will be useful for you.
https://github.com/antonkomarev/laravel-love-upgrade
