### ISSUE TITLE
Error: "Reacter not exists"

### ISSUE THREAD

**Issue by sburkett** [cybercog/laravel-love#125]
I followed the setup instructions for the default reaction types, and a nullable Reacterable and a nullable Reactable. 

I then added the appropriate lines to my `User` and `Entry` models:

```
<?php

namespace App\Models;

use Cog\Contracts\Love\Reactable\Models\Reactable as ReactableContract;
use Cog\Laravel\Love\Reactable\Models\Traits\Reactable;

use Illuminate\Database\Eloquent\Model;
  
class Entry extends Model implements ReactableContract
{
  use Reactable;
  ...
}
```

```
<?php

namespace App\Models;

use Cog\Contracts\Love\Reacterable\Models\Reacterable as ReacterableContract;
use Cog\Laravel\Love\Reacterable\Models\Traits\Reacterable;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
  
class User extends Authenticatable implements ReacterableContract
{ 
  use Reacterable;
  ...
}  
```

I then tested as follows via a simple test controller:

```
public function foo( Request $request )
{
    $entry = Entry::find(8); // Just a quick entry for testing purposes
    $user = Auth::user();

    $reacterFacade = $user->viaLoveReacter();
    $reacterFacade->reactTo($entry, 'Like');
}
```

The above throws a `ReacterInvalid` exception:

![image](https://user-images.githubusercontent.com/2219483/68091890-6d3d8600-fe53-11e9-824d-c7e35586ff1c.png)

I did a `dd()` on `$user` (as the reacter), and it returns the currently authenticated user, but I don't see anything under `relation` (which I might think would be there for this package?):

![image](https://user-images.githubusercontent.com/2219483/68091923-bb528980-fe53-11e9-953b-96167eca5f38.png)

Any ideas?

**Comment by antonkomarev** [comment]
If user was created before the package integration - then `love_reacter_id` value will be `null`. If so - then issue #105 will be helpful. All you need - register user as reacter. I designed this package with an ability to define if user is able to react to the reactants.

This is another one issue which describes a programmable console solution for auto-registering all the reacter\reactant models: #106

**Comment by sburkett** [comment]
Ah, ok. That makes sense. Works terrific now!

**Comment by alkaou** [comment]
Hello, how can i to get all users has reacted in a post ?

**Comment by antonkomarev** [comment]
@alkaou this is not related to this issue.

```php
$reactions = $post->viaLoveReactant()->getReactions();

foreach ($reactions as $reaction) {
    $user = $reaction->getReacter()->getReactable();
    dump($user);
}
```
