### ISSUE TITLE
Laravel/Love Wiki

### ISSUE THREAD

**Issue by sburkett** [cybercog/laravel-love#126]
For the benefit of users, I recommend you enable the Wiki option for the repo here. If nothing else, it can be used for recipes, tutorials, etc. Just a thought :)

**Comment by antonkomarev** [comment]
I haven't thought about GitHub Wiki in that way. Enabled Wiki option.

**Comment by sburkett** [comment]
Awesome!

**Comment by antonkomarev** [comment]
Feel free to write some info there :+1:
