### ISSUE TITLE
How to display reactions count in blade

### ISSUE THREAD

**Issue by SurfJunky** [cybercog/laravel-love#130]
Do i have to make a relationship to show counts off likes / dislikes for example on each comment.

**Comment by antonkomarev** [comment]
If you want to use optimized way - use Reactant Facade:

```php
$reactantFacade = $comment->viaLoveReactant();
```

## Reaction Counters

Each `Reactant` has many counters (one for each reaction type) with aggregated data.

### Get reaction counters of reactant

```php
$reactionCounters = $reactantFacade->getReactionCounters();
```

### Get reaction counter of exact type

```php
$reactionCounter = $reactantFacade->getReactionCounterOfType('Like');
```

## Reaction Totals

Each `Reactant` has one total with aggregated data. Total is sum of counters of all reaction types.

### Get reaction total of reactant

```php
$reactionTotal = $reactantFacade->getReactionTotal();
```

**Comment by SurfJunky** [comment]
> 
> 
> If you want to use optimized way - use Reactant Facade:
> 
> ```
> $reactantFacade = $comment->viaLoveReactant();
> ```
> 
> ### Reaction Counters
> 
> Each `Reactant` has many counters (one for each reaction type) with aggregated data.
> ### Get reaction counters of reactant
> 
> ```
> $allReactionCounters = $reactantFacade->getReactionCounters();
> ```
> 
> #### Get reaction counter of exact type
> 
> ```
> $reactionLikeCounter = $reactantFacade->getReactionCounterOfType('Like');
> ```
> 
> ### Reaction Totals
> 
> Each `Reactant` has one total with aggregated data. Total is sum of counters of all reaction types.
> ### Get reaction total of reactant
> 
> ```
> $reactionTotal = $reactantFacade->getReactionTotal();
> ```

Thanks for answer my question,
but i have a problem define the reactant object in my case

Here is the controller 
` public function show($slug)
    {
        $article = Article::where('slug', $slug)->firstOrFail();
      
        $comments = $article->comments;
        $reactantFacade = $comment->viaLoveReactant();
        $countLikes = $reactantFacade->getReactionCounterOfType('Like');
        $likes= $CountLikes->getCount();
        
        return view('blog.article', compact('article', 'comments', 'likes'));

    }

Blade view 
`{{$likes}}`

`Returns
Undefined variable: comment

**Comment by antonkomarev** [comment]
What are you trying to receive? Total likes count in all of the comments or you need to display likes count in each comment item?

**Comment by SurfJunky** [comment]
display likes count in each comment item

**Comment by antonkomarev** [comment]
Here is your modified controller:
```php
public function show($slug)
{
    $article = Article::where('slug', $slug)->firstOrFail();

    $comments = $article->comments;
        
    return view('blog.article', compact('article', 'comments'));
}
```

In blade view:
```php
@foreach ($comments as $comment)
    Likes: {{ $comment->viaLoveReactant()->getReactionCounterOfType('Like')->getCount() }}
@endforeach
```

**Comment by SurfJunky** [comment]
> 
> 
> Here is your modified controller:
> 
> ```
> public function show($slug)
> {
>     $article = Article::where('slug', $slug)->firstOrFail();
> 
>     $comments = $article->comments;
>         
>     return view('blog.article', compact('article', 'comments'));
> }
> ```
> 
> In blade view:
> 
> ```
> @foreach ($comments as $comment)
>     Likes: {{ $comment->viaLoveReactant()->getReactionCounterOfType('Like')->getCount() }}
> @endforeach
> ```

Works likes a chrome :)

Thank you :3

**Comment by antonkomarev** [comment]
If you will have too many database requests you could use some Eloquent [eager loading](https://laravel-love.readme.io/v8.0/docs/eager-loading) magic.
```php
$article = Article::query()
    ->where('slug', $slug)
    ->with([
        'comments',
        'comments.loveReactant.reactionCounters',
    ])
    ->firstOrFail();
```

**Comment by SurfJunky** [comment]
> 
> 
> If you will have too many database requests you could use some Eloquent [eager loading](https://laravel-love.readme.io/v8.0/docs/eager-loading) magic.
> 
> ```
> $article = Article::query()
>     ->where('slug', $slug)
>     ->with([
>         'comments',
>         'comments.loveReactant.reactionCounters',
>     ])
>     ->firstOrFail();
> ```

Alright thanks for this hint too, i appreciate your efforts 
Thanks so much <3

**Comment by antonkomarev** [comment]
If you don't want to simplify your blade views you could add helper method to your `Comment` model:
```php
class Comment extends Model
{
    // ... your model code

    public function getLikesCount(): int
    {
        return $this->viaLoveReactant()->getReactionCounterOfType('Like')->getCount();
    }
}
```

Then instead of:
```php
@foreach ($comments as $comment)
    Likes: {{ $comment->viaLoveReactant()->getReactionCounterOfType('Like')->getCount() }}
@endforeach
```

You will write:
```php
@foreach ($comments as $comment)
    Likes: {{ $comment->getLikesCount() }}
@endforeach
```
