### ISSUE TITLE
How to delete all reactions made by the User (unreactAll)?

### ISSUE THREAD

**Issue by wimil** [cybercog/laravel-love#131]
There is some method to erase all the reactions that a reacter has reacted to.

example something like unreactTo but all would be unreactAll

**Comment by antonkomarev** [comment]
Could you provide a use-case for this feature, please?

Reacter's `unreactTo` method just trying to find reaction from the `Reacter` related to `Reactant` model and then deletes it. So you can do it manually in a pretty trivial way: 

```php
$reactions = $user->viaLoveReacter()->getReactions();
foreach ($reactions as $reaction) {
    $reaction->delete();
}
```

If you will just delete reactions directly from the database plain SQL query - then Laravel Eloquent model events wouldn't be fired and reaction counters will be un-synced.

**Comment by wimil** [comment]
I am using Facebook reactions, a user can react with a "pisses me off", but he can change his reaction to a "like".
How could I do that? If the only way is to eliminate the reaction, and save the new reaction, now the unreactTo method only eliminates by type of reaction, then I would have to bring the reaction to get the type, and then eliminate

**Comment by antonkomarev** [comment]
Ah, now I see your requirement.

That happens because you are calling delete method of the Query Builder instead of the Eloquent Model. Fetch all reactions first and then delete each.

```php
$reactions = $this->reactions()->where('reactant_id', $reactant->getId())->get();
foreach ($reactions as $reaction) {
    $reaction->delete();
}
```

Or use some Laravel magic if you like:
```php
$reactions = $this->reactions()->where('reactant_id', $reactant->getId())->get();
$reactions->each->delete();
```

**Comment by wimil** [comment]
Thanks for the help, I created a method called "ureactFirst" that brings the first result and eliminates it, so use the eloquent and activate the events

```php
public function unreactFirst(ReactantContract $reactant): void
    {
        if ($reactant->isNull()) {
            throw ReactantInvalid::notExists();
        }
        $this
            ->reactions()
            ->where('reactant_id', $reactant->getId())
            ->first()
            ->delete();
    }
```

**Comment by antonkomarev** [comment]
If user is allowed to create only one reaction, that should work. If this method located in your application's `User` model, I'd recommend you to rely on `Cog\Contracts\Love\Reactable\Models\Reactable` contract instead of `Cog\Contracts\Love\Reactant\Models\Reactant`. Then your application logic will be less coupled with Love package implementation.

```php
use Cog\Contracts\Love\Reactable\Models\Reactable as ReactableContract;

public function unreactFirst(ReactableContract $reactable): void
{
    $reactant = $reactable->getLoveReactant();

    if ($reactant->isNull()) {
        throw ReactantInvalid::notExists();
    }

    $this
        ->reactions()
        ->where('reactant_id', $reactant->getId())
        ->first()
        ->delete();
}
```

Instead of:
```php
$user->unreactTo($comment->getLoveReacter());
```

You will write:
```php
$user->unreactFirst($comment);
```

You can see how better your code looks like by using [Reacter Facade](https://laravel-love.readme.io/v8.0/docs/reacter-facade) & [Reactant Facade](https://laravel-love.readme.io/v8.0/docs/reactant-facade).

**Comment by wimil** [comment]
thank you very much for the advice and help
