### ISSUE TITLE
Get likes and relation of user

### ISSUE THREAD

**Issue by lahed** [cybercog/laravel-love#14]
Hello,
I want to get the places that have like, I do this:
`$users = $place->likes()->paginate();`

How do I get the user's relationship to get the name for example?
`dd($users[0]->user->name);`

Is the relationship missing?

Thanks!

**Comment by a-komarev** [comment]
Hello @lahed! Thank you for the good question. I'm finishing one of my projects and plan to refactor an API accordingly to the specification: https://github.com/cybercog/laravel-love/issues/7
Then it should be available out from the box.
You could [extend `Like` model](https://github.com/cybercog/laravel-love#use-model-class-own-implementation) and add any methods you need for now.

**Comment by lahed** [comment]
Thank you!
