### ISSUE TITLE
non-nullable Reactants

### ISSUE THREAD

**Issue by volkv** [cybercog/laravel-love#140]
Hi. Docs saying 

> Remove --nullable flag if all models of this type must be reacterable:
> 
> $ php artisan love:setup-reacterable --model="App\User"

How should it  work if you observe Created event which is fired after model is inserted into DB (which is not possible with non-nullable field)..?

**Comment by antonkomarev** [comment]
Hi @volkv! Initially I've thought that it might be useful when you are implementing your own logic. But it will require to implement your own models and observers. To be honest I've never used non-nullable fields.

**Comment by antonkomarev** [comment]
I think it will be better to add `--non-nullable` flag in future versions and make this command to generate nullable fields by default.

**Comment by farhanianz** [comment]
I just checked it does not work if --nullable is not added while setting up reacters. Seems like the created events is not fired as @volkv said before. 

Same goes for setting up reactants.
