### ISSUE TITLE
Unable to check status of likeBy();

### ISSUE THREAD

**Issue by focusiq** [cybercog/laravel-love#16]
I am trying to check the status of likeBy() method, but can't, as it returns a void. When a user who has liked a model tries I want to return a a boolean instead of the void that is returned by the package.

I already tried to check 
`$like = $agent->likeBy($user->id);
if($like)
{
dd('success')
}
dd('failed')
`
but it keeps going down to failed! Any solution for this?

**Comment by focusiq** [comment]
Just discovered i can use the 
`$article->isLikedBy($user->id)`

to check status, but wouldn't it be better to get the status from
`$like = $agent->likeBy($user->id);`

Thanks.

**Comment by antonkomarev** [comment]
@focusiq if `likeBy` method not throws `\Cog\Contracts\Love\Liker\Exceptions\InvalidLiker` exception - then you could be sure that model was liked successfully. Otherwise exception will be thrown and you will be sure that it's failed for a reason.

**Comment by antonkomarev** [comment]
```php
try {
    $agent->likeBy($user->id);
    // Here goes successful execution logic
} catch (\Cog\Contracts\Love\Liker\Exceptions\InvalidLiker $exception) {
    dd('Something wrong!');
    // Here goes error logic
}
```
