### ISSUE TITLE
Why records in love_reactant_reaction_counters table are not creating?

### ISSUE THREAD

**Issue by coral4host** [cybercog/laravel-love#160]
hey @antonkomarev 
Am trying to use the react to function, 
the new react has been stored successfully in _love_reactions_ table, while cannot store the related records in _love_reactant_reaction_counters and love_reactant_reaction_totals_
so I cannot get the reaction count!

here is my code for following up: 
Am using **MySQL 5.6

```php
function reactTo($type,  $weight = 1)
    {
        $user = getAuthUser();
        if ($user){
            // get reaction type
            if (is_null($type)){
                $type = 'like';
            }
            $reactionType = ReactionType::fromName($type);
            $typeName = $reactionType->getName(); 

            if ($this->isNotRegisteredAsLoveReactant()){
                $this->registerAsLoveReactant();
            }

            if ($user->isNotRegisteredAsLoveReacter()){ // false
                $user->registerAsLoveReacter();
            }
            $reacterFacade = $user->viaLoveReacter();

            $isNotReacted = $reacterFacade->hasNotReactedTo($this);
            if ($isNotReacted){
                $reacterFacade->reactTo($this, $typeName, $weight);
            }
        }
        return false;
    }
```

**Comment by antonkomarev** [comment]
First of all - I'm not sure you need to make these checks all the time:
```php
if ($this->isNotRegisteredAsLoveReactant()){
    $this->registerAsLoveReactant();
}

if ($user->isNotRegisteredAsLoveReacter()){ // false
    $user->registerAsLoveReacter();
}
```

I'd suggest to simplify your code to make it like this:
```
function reactTo($type,  $weight = 1)
{
    $user = getAuthUser();
    if (!$user) {
        return false;
    }

    if (is_null($type)){
        $type = 'like';
    }

    try {
        $user->viaLoveReacter()->reactTo($this, $type, $weight);
    } catch (\Cog\Contracts\Love\Reaction\Exceptions\ReactionNotExists $exception) {
        return false;
    }
}
```

**Comment by antonkomarev** [comment]
Second, if your service using queues - counters and totals will be created using them. You need to use `sync` queue driver or run queue watch while testing your app locally.

**Comment by coral4host** [comment]
hey @antonkomarev 

Firstly, really appreciate your fast reply 

I've tried your changes, the issue hasn't solved, unfortunately.

But to be more clear my code is working well on **MySQL 5.7**, the problem only with **MySQL 5.6**
so any suggestion? or changes in the package codes to get it to work with 5.6?

**Comment by antonkomarev** [comment]
That seems really strange. Could you check for mysql error logs?
I don't know any difference between these versions which could be the reason of this.

**Comment by coral4host** [comment]
I've checked MySQL error log and laravel error log, no error related to the issue, 
maybe not related to the MySQL version! but still not work.
any other suggestions? 
records on **love_reactions** stored successfully
will there is no records in ### love_reactant_reaction_counters and love_reactant_reaction_totals

**Comment by antonkomarev** [comment]
What version of Laravel Love are you using?

**Comment by coral4host** [comment]
v5.7.29

**Comment by coral4host** [comment]
laravel love 8.3.1
laravel framework 5.7.29
php version 7.1.33

**Comment by antonkomarev** [comment]
Creation of counter should be done after this event is dispatched:
`Cog\Laravel\Love\Reaction\Events\ReactionHasBeenRemoved`

Then listeners handle this event:
`Cog\Laravel\Love\Reactant\Listeners\IncrementAggregates`

It dispatches the async job:
`Cog\Laravel\Love\Reactant\Jobs\IncrementReactionAggregatesJob::handle`

Concrete creation is happening here:
`Cog\Laravel\Love\Reactant\ReactionCounter\Services\ReactionCounterService::findOrCreateCounterOfType`
```php
private function findOrCreateCounterOfType(
    ReactionTypeContract $reactionType
): ReactionCounterContract {
    $counter = $this->findCounterOfType($reactionType);
    if ($counter instanceof NullReactionCounter) {
        $this->reactant->createReactionCounterOfType($reactionType);
        $counter = $this->findCounterOfType($reactionType);
    }

    return $counter;
}
```

You could try to add some `dump('something')` in vendor directory and try to understand what is happening and why counter model is not creating.

**Comment by coral4host** [comment]
@antonkomarev was debugging the code for a while by log::info , and
I found that the application is not dispatching class ReactionHasBeenRemoved, 
OR getReaction() seems not working and not showing any logs from there. could you give me some steps back to keep checking?

**Comment by antonkomarev** [comment]
Sorry, I was too tired when that comment, on create reaction `ReactionHasBeenAdded` is dispatched, not `ReactionHasBeenRemoved`, but anyway, both of this events should check for counter existence. I've fixed text in comment.

You are calling `reactTo`, it checks if reaction already exists, if not - it executes `createReaction` method which just a wrapper for `Reaction` Eloquent model creation:
```php
$this->reactions()->create([
    'reaction_type_id' => $reactionType->getId(),
    'reactant_id' => $reactant->getId(),
    'rate' => $rate,
]);
```

Reaction model is observed by the `Cog\Laravel\Love\Reaction\Observers\ReactionObserver` class, so right after model creation it just dispatches `ReactionHasBeenAdded` event. And counters are waiting for this event to be updated.

You could try to add debugging in `\Cog\Laravel\Love\Reaction\Observers\ReactionObserver::created` method. If it's not executing - it will mean only one thing - that `ReactionObserver` not observing `Reaction` model.

Observers are registering in `Cog\Laravel\Love\LoveServiceProvider::registerObservers` method. If this not happening - the only one thing is in my mind: [package discovery](https://laravel.com/docs/7.x/packages#package-discovery) disabled in your application.

If there is a reason for it - you may register Laravel Love service providers manually in `config/app.php` file. There is `providers` array in this config file, add 2 providers right before the `Application Service Providers`:

```
/*
 * Package Service Providers...
 */
Cog\Laravel\Love\LoveServiceProvider::class,
Cog\Laravel\Love\LoveEventServiceProvider::class,

/*
 * Application Service Providers...
 */
```

**Comment by coral4host** [comment]
Hollaaa, solved after registering the Laravel Love service providers manually in config/app.php.
really appreciate your help and reply <3.

**Comment by antonkomarev** [comment]
Glad you found solution.
