### ISSUE TITLE
get reaction name from getReactionCounters()

### ISSUE THREAD

**Issue by jayenne** [cybercog/laravel-love#166]
hi,
I'm fighting with this package a bit owing to the lack of examples and have a bunch on quesitons.

In order to keep the processing to a minimum, I would like to get the name of the reaction from the getReactionCounters(). currently I don't think this is possible. or is it?
* I don't seem to be able to see a way to get love_reaction_type table data from getReactionCounters()

Would you have an example to achieve this please?

**Comment by antonkomarev** [comment]
Try this one:
```php
$reactantFacade = $comment->viaLoveReactant();
$counters = $reactantFacade->getReactionCounters();

foreach ($counters as $counter) {
    dd($counter->getReactionType());
}
```

**Comment by jayenne** [comment]
Thanks for this Anton, I was doing this in a round about way but thought there might be a short route.
 
Aslo, is there a way to return a full list of reaction_types too? (for creating UI)

**Comment by antonkomarev** [comment]
How do you see it? What format do you want to get this list in?

**Comment by jayenne** [comment]
Ideally, I'd like to call a method that returns the contents of the entire love_reation_types table.
I can then loop it to create my json.

```
$['id' => n, 'name' => 'foo', 'mass' => n.n, 'created_at' => NULL, 'updated_at' => NULL]
```

**Comment by antonkomarev** [comment]
If you want to get just all reaction types you could always do:
```php
$reactionTypes = ReactionType::all();
```

**Comment by jayenne** [comment]
thnkas you. have a great weekend.

**Comment by antonkomarev** [comment]
I've added `getReactionType` method to documentation.

**Comment by jayenne** [comment]
> If you want to get just all reaction types you could always do:
> 
> ```
> $reactionTypes = ReactionType::all();
> ```

Sorry Anton .this is a dumb one...How exactly would I use that ^ in a crontroller (or fractal transformer )?
I need  the `mass` of a `reaction_type` by `name` (or `id`) but as it's not had a reaction yet it's not in any counter.

**Comment by antonkomarev** [comment]
If you only need to get `name => mass` array - you can do:

```php
$reactionTypes = ReactionType::all()->pluck('mass', 'name')->toArray();
```

I don't clearly understand what exactly the issue is?

**Comment by jayenne** [comment]
yeah sorry,
I put in a controller and get "Class 'ReactionType' not found"

**Comment by antonkomarev** [comment]
Yes, you should import class:
```php
use Cog\Laravel\Love\ReactionType\Models\ReactionType;
```

**Comment by jayenne** [comment]
perfect. thank you. I'd been inadvertantly including the ReactionType contract instead.
```use Cog\Contracts\Love\ReactionType\Models\ReactionType;```
