### ISSUE TITLE
Reacter not exists

### ISSUE THREAD

**Issue by tojorodialson** [cybercog/laravel-love#168]
Hello everyone,
Thanks for this library.

I use this code in my models **Users**

```
use Cog\Contracts\Love\Reacterable\Models\Reacterable as ReacterableContract;
use Cog\Laravel\Love\Reacterable\Models\Traits\Reacterable;

class Users extends Authenticatable implements Following, ReacterableContract {

    use Reacterable;
}
```
and this in my post table

```
use Cog\Contracts\Love\Reactable\Models\Reactable as ReactableContract;
use Cog\Laravel\Love\Reactable\Models\Traits\Reactable;

class PostUsers extends Model implements ReactableContract {

    use Reactable;
}
```

The user would make like on table post

After manipulation I receive this error below

```
Cog\Contracts\Love\Reacter\Exceptions\ReacterInvalid
Reacter not exists.
```

Can you help me please?

**Comment by antonkomarev** [comment]
@tojorodialson all new users should auto-register as reacters, but if you are integrating package on already existing user base you need to register your Reacterable models as Reacters first. Just run console command:

```shell script
php artisan love:register-reacters --model="App\User"
```

**Comment by tojorodialson** [comment]
It must execute this for all news users?

**Comment by antonkomarev** [comment]
New users will auto-register. You need to execute it only once after package integration.
