### ISSUE TITLE
[Proposal] extend the type of reaction.

### ISSUE THREAD

**Issue by yaquawa** [cybercog/laravel-love#17]
Hi, 
thanks for the great work!

Just like facebook there could be more than just 'like' or 'dislike', for example, 'sad', 'angry' or whatever you can imagine. Having this flexibility can extend the use case of this package.👍🏼

**Comment by antonkomarev** [comment]
Hello, @yaquawa!
This functionality is in progress in v6 branch. You could see how this functionality will be implemented on diagram in #15.

**Comment by yaquawa** [comment]
@antonkomarev Looks yummy🤤 Looking forward to the next version!

**Comment by antonkomarev** [comment]
PR #24 was merged. Laravel Love v6 will be released soon.

With new API we will be able to have any reaction types we want.
```php
$sadType = ReactionType::fromName('Sad');
$angryType = ReactionType::fromName('Angry');

$reacter = $user->getReacter();
$reactant = $article->getReactant();

$reacter->reactTo($reactant, $sadType);
$reacter->reactTo($reactant, $angryType);
```

> **Note:** You can instantiate reaction type from name only if reaction type with such name exists, otherwise exception will be thrown.
