### ISSUE TITLE
Change table name?

### ISSUE THREAD

**Issue by WithMira** [cybercog/laravel-love#18]
Is it possible to change the name of the table through the configuration?

**Comment by antonkomarev** [comment]
Hello @WithMira!
Sorry, this package is not designed this way. The only way to do it - create own `Like` model and re-bind it in your own application service provider. In the next version there is no plans to add database configuration too.
Why do you need it? I understand case when application has database table names conflicts, but this package has `love_` prefix on each table, so name conflicts are minimized as much as possible.

**Comment by WithMira** [comment]
I use prefix in the names of tables.
@antonkomarev , Thank you for your fast reply.

**Comment by antonkomarev** [comment]
Here is an [Extending section](https://github.com/cybercog/laravel-love#extending) in documentation where you could find how to overwrite default Like model with your custom one.
