### ISSUE TITLE
NotAssignedToReactable exception when trying to access deleted item

### ISSUE THREAD

**Issue by Marchiuzzz** [cybercog/laravel-love#189]
Hi, I have noticed an issue when trying to access the reactable object from a reaction like so 
`$item->getReactant()->getReactable()` for a deleted item (an object that uses soft deletes)
I just get thrown NotAssignedToReactable exception, shouldn't it handle this on it's own?

**Comment by antonkomarev** [comment]
You cannot get soft deleted Reactable model from the Reactant using `getReactable` method at this moment, but you can do it this way:
```php
`$item->getReactant()->reactable()->withTrashed()->first()`
```

**Comment by Marchiuzzz** [comment]
Thanks for the workaround! Though I already figured another way to tackle this, with try-catch, if trying to get reactable throws an error, I know that item was deleted.
