### ISSUE TITLE
methods available for the view

### ISSUE THREAD

**Issue by bertux77** [cybercog/laravel-love#194]
I wanted to ask if there is any method to use in the views, for example:

$comment->getTotalLikes; ?

**Comment by antonkomarev** [comment]
@bertux77 I think that Reactant Facade is what are you looking for: https://laravel-love.readme.io/docs/reactant-facade

```php
$comment->viaLoveReactant()->getReactionTotal()->getCount();
```

**Comment by bertux77** [comment]
Thank you very much for your quick response

**Comment by antonkomarev** [comment]
If you have any questions accordingly to this topic feel free to continue conversation here. If there are any other questions - create a new issue.
