### ISSUE TITLE
eager loading

### ISSUE THREAD

**Issue by bertux77** [cybercog/laravel-love#195]
Hello!
Maybe my question is very stupid, but I'm quite new to this.
Is it possible to make a query with eager loading to bring all the comments with likes and dislikes totals and at the same time have the option checked if the user has liked or disliked?

**Comment by antonkomarev** [comment]
Here is an example
https://laravel-love.readme.io/docs/eager-loading

**Comment by bertux77** [comment]
sorry I didn't check before asking.
