### ISSUE TITLE
Laravel 5.7 support

### ISSUE THREAD

**Issue by hassanazimi** [cybercog/laravel-love#20]
Trying to update from 5.6 to 5.7 i get this message:

```
Problem 1
    - Conclusion: don't install cybercog/laravel-love 5.1.1
    - Conclusion: don't install laravel/framework v5.7.2
    - Installation request for cybercog/laravel-love ^5.1 -> satisfiable by cybercog/laravel-love[5.1.0, 5.1.1].
    - Conclusion: don't install laravel/framework v5.7.1
    - cybercog/laravel-love 5.1.0 requires illuminate/database ~5.5.0|~5.6.0 -> satisfiable by illuminate/database[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
```

and so on

**Comment by antonkomarev** [comment]
@hassanazimi yeah. Planned to update all my packages for today.

**Comment by antonkomarev** [comment]
There are issues with testing platform in latest version. Waiting for the response: https://github.com/orchestral/testbench/issues/229

**Comment by antonkomarev** [comment]
@hassanazimi Laravel 5.7 support added in Laravel Love v5.2.0 release

**Comment by hassanazimi** [comment]
@antonkomarev thanks brother. great package. love it.

**Comment by hassanazimi** [comment]
Also please update the packagist composer i am pulling form there. Thanks

**Comment by antonkomarev** [comment]
It seems that GitHub services will be deprecated soon and packagist haven't auto-updated release. Made it manually. Thanks for the report!

> This package is using the legacy GitHub service and will stop being auto-updated in early 2019. Please set up the new GitHub Hook for Packagist so that it keeps working in the future.
