### ISSUE TITLE
Add support for laravel 9

### ISSUE THREAD

**Issue by WimDeMeester** [cybercog/laravel-love#204]
Is it possible to add support for laravel 9?

**Comment by antonkomarev** [comment]
Sure, I will try to find time for it ASAP. If you want to speed it up, make MR.

**Comment by antonkomarev** [comment]
@WimDeMeester done in #206
[Laravel Love v8.9](https://github.com/cybercog/laravel-love/releases/tag/8.9.0) has been released with Laravel 9 support.
