### ISSUE TITLE
Does it work with factory or seeder?

### ISSUE THREAD

**Issue by itsrafsanjani** [cybercog/laravel-love#208]
Normal registration and login are working fine. But when I try to use UserSeeder/UserFactory it's not working. It gets stuck after one insert into the users table.

**Comment by antonkomarev** [comment]
Maybe because you have not nullable `love_` column in users table?

**Comment by itsrafsanjani** [comment]
No that's already nullable. I tried to reproduce it with a new project. But it works fine. 
Maybe there is some problem with observers in my project.
When I run `withoutEvents` it works.
Then I have run these commands.
```
php artisan love:register-reacters --model="App\Models\User"
php artisan love:register-reactants --model="App\Models\User"
```

BTW I'm using User model for both `reacter` and `reactant`.

If anyone has this problem please mention me again.

**Comment by itsrafsanjani** [comment]
Damn, I have found the problem. At the same time, there was 2 observer running, my own `UserObserver` and `Reacterable/Reactable Observer`. Both tried to update the User model. That's why it got stuck.

**Comment by antonkomarev** [comment]
Thanks for share it. Issue could be closed?

**Comment by itsrafsanjani** [comment]
Yeah, sure.
