### ISSUE TITLE
Database Changes - Setup Instructions

### ISSUE THREAD

**Issue by JD456976** [cybercog/laravel-love#213]
Change:

```
php artisan love:setup-reacterable --model="App\User"
```

To:

```
php artisan love:setup-reacterable --model="App\Models\User"
```

**Comment by antonkomarev** [comment]
Models could be anywhere you want. Models directory is a pretty new standard in Laravel, earlier it was in the app root.

**Comment by antonkomarev** [comment]
@JD456976 Fixed it, thanks!

**Comment by JD456976** [comment]
Very welcome!

Thank you for all your work on your package!
