### ISSUE TITLE
Get Reacterable for soft deleted (trashed) users

### ISSUE THREAD

**Issue by schwemmer** [cybercog/laravel-love#238]
We have a bunch of soft deleted users and would like to still count their reactions (shown as "Deleted User"). The easiest way to do this is to change the relationship in the Reacter Model from this:

```
public function reacterable(): MorphTo
{
        return $this->morphTo('reacterable', 'type', 'id', 'love_reacter_id');
}
```
to this:

```
public function reacterable(): MorphTo
{
        return $this->morphTo('reacterable', 'type', 'id', 'love_reacter_id')->withTrashed();
}
```

However, the class is final and can not be extended. It would be great if we could somehow pass a parameter to also get reactions from soft deleted users in a future release.

See also  #189

**Comment by antonkomarev** [comment]
Can you call `withTrashed` like in issue you provided?

```php
$item->getReacter()->reacterable()->withTrashed()->first()
```

**Comment by antonkomarev** [comment]
@schwemmer another one way to do this:
1. Copy `\Cog\Laravel\Love\Reacter\Models\Reacter` model to your app namespace
2. Modify `reacterable` method to fit your needs
3. Override `loveReacter` method in your User (Reacterable) model (it should return custom Reacter model)

**Comment by schwemmer** [comment]
Thanks a lot @antonkomarev, the first way you mentioned above actually works great!

**Comment by antonkomarev** [comment]
Can we close an issue?

**Comment by schwemmer** [comment]
Yes, thank you!
