### ISSUE TITLE
cannot use custom migrations even after publishing them

### ISSUE THREAD

**Issue by vesper8** [cybercog/laravel-love#28]
It seems that as a result of the PR here https://github.com/cybercog/laravel-love/pull/11

Even if you publish the migrations, the changes are ignored and instead the package's migrations are used.

On a side note, I personally feel that it was ok how you were doing it before, that in order to use the package the user is required to publish the migrations first.. this is how 90% of packages that depend on migrations are doing it.. and it leaves more flexibility

So I would just revert that PR and include publishing the migrations in the docs, which you already do.

**Comment by antonkomarev** [comment]
Hmmm... @vesper8 are you sure? It's default Laravel behavior. If migration exists locally - it will be used instead of the package one. Have you tried to call `composer dump`?

**Comment by vesper8** [comment]
I have just now.. it's very weird.. the love_likes custom migration is respected but the love_likes_counters is not

if I comment out ```$this->loadMigrationsFrom(__DIR__ . '/../../database/migrations');````

from the LoveServiceProvider then both of my custom migrations are respected

The only difference I'm doing in the custom migrations is I am creating the tables on a different database than the 'primary' one

**Comment by antonkomarev** [comment]
Wait a moment... second table is called `love_like_counters` like without `s` on the end. Maybe it's a reason of conflict?

**Comment by vesper8** [comment]
Yes.. that was just a type.. I am not messing with the table names

Anyway I managed to fix it now, what I did is I changed the timestamp on my custom migrations so the date is earlier than the ones from the package

This way mine are always run first and I guess that prevents the package's from being run.. this works

Don't know why the erratic behaviour.. but I guess you can close this

**Comment by vesper8** [comment]
and thanks for the quick support :)

**Comment by antonkomarev** [comment]
Thank you for writing the resolution. These migration timestamp issues sometimes are real pain.

**Comment by vesper8** [comment]
honestly don't know what's going on but my fix isn't working anymore and I'm having a new problem now where it says that it cannot redeclare the class of the duplicate migration

so I just made my own "migrations:fresh" script and added this line to comment out your migrations from the LoveServiceProvider.php

```
`sed -i '/\$this->registerMigrations();/s/^/\/\//g' ./vendor/cybercog/laravel-love/src/Providers/LoveServiceProvider.php`;

```

**Comment by antonkomarev** [comment]
You can check if there are same migration names in `migrations` table records. Maybe it differ somehow.

**Comment by JFunu** [comment]
I am having sames issues, where after publishing the migration files, my custom migration files are conflicting with the package's migrations files. I want to suggest if there can be an option to turn of the package migration like is done with laravel passport where you can this <code> Passport::ignoreMigrations</code> to your AppServiceProvider.

**Comment by antonkomarev** [comment]
@JFunu I'll try to find time for it ASAP. Add PR if you want to do have this feature earlier.

**Comment by antonkomarev** [comment]
This feature will be designed in #71 issue.
