### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by joveice** [cybercog/laravel-love#29]
Hey, I followed the documentation and this is what I found
Here:
```
Prepare Liker Model
Use Cog\Contracts\Love\Liker\Models\Liker contract in model which will get likes behavior and implement it or just use Cog\Laravel\Love\Liker\Models\Traits\Liker trait.

use Cog\Contracts\Love\Liker\Models\Liker as LikerContract;
use Cog\Laravel\Love\Liker\Models\Traits\Liker;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable implements LikerContract
{
    use Liker;
}
```

> Use Cog\Contracts\Love\Liker\Models\Liker contract in model which will get likes behavior and implement it or just use Cog\Laravel\Love\Liker\Models\Traits\Liker trait.

I tried first with the trait, gave an error, then I tried with the contract and implement it, gave an error, then I did both and it worked. The documentation said "or".
Same goes for the likeable.

Or did I do something wrong?

**Comment by antonkomarev** [comment]
I was wanted to say:
1. Use contract
2. Implement it or use trait

I think there should be better way to describe it. If you could rephrase it - PRs are welcomed!

**Comment by joveice** [comment]
@antonkomarev ah I see! No problem. My primary language isn't English so I won't be doing any rephrasing, I just thought the documentation was wrong.

Great package you have created here, really help full, and really well done! Definitely gonna be my go to package for this.
