### ISSUE TITLE
Add Likes Statistics Service

### ISSUE THREAD

**Issue by antonkomarev** [cybercog/laravel-love#3]
### What to do

1. Count likes of the Entity within date.
2. Count dislikes of the Entity within date.
3. Count likes\dislikes of the Entity within date.
4. Get all the Entities which were liked within date (with likes meta info).
5. Get all the Entities which were disliked within date (with likes meta info).
6. Get all the Entities which were likes\disliked within date (with likes meta info).

### Where Scopes

- Add method `scopeWhereLikedByDate` to service layer.
- Add method `scopeWhereLikedByDate` to Likeable models.
- Add method `scopeWhereLikedBetweenDates` to service layer.
- Add method `scopeWhereLikedBetweenDates` to Likeable models.
- Add method `scopeWhereDislikedByDate` to service layer.
- Add method `scopeWhereDislikedByDate` to Likeable models.
- Add method `scopeWhereDislikedBetweenDates` to service layer.
- Add method `scopeWhereDislikedBetweenDates` to Likeable models.

### Counters

- Add method `countLikesByDate` to service layer.
- Add method `countLikesByDate` to Likeable models.
- Add method `countLikesBetweenDates` to sevice layer.
- Add method `countLikesBetweenDates` to Likeable models.

#### Split LikeableService by adding CounterService (?)

- Move method `incrementLikesCount` to `CounterService` from `LikeableService`
- Move method `decrementLikesCount` to `CounterService` from `LikeableService`
- Move method `incrementDislikesCount` to `CounterService` from `LikeableService`
- Move method `decrementDislikesCount` to `CounterService` from `LikeableService`
- Move method `removeLikeCountersOfType` to `CounterService` from `LikeableService`
- Move method `scopeOrderByLikesCount` to `CounterService` from `LikeableService`
- Move method `fetchLikesCounters` to `CounterService` from `LikeableService`

**Comment by a-komarev** [comment]
Counts by date could use [Counting related models](https://laravel.com/docs/5.4/eloquent-relationships#counting-related-models)

**Comment by antonkomarev** [comment]
This feature is on hold before v7 because I've completely revised an API of the next package version.
More details about v6: https://github.com/cybercog/laravel-love/issues/15
