### ISSUE TITLE
Egear loader on like and dislike count

### ISSUE THREAD

**Issue by popouille** [cybercog/laravel-love#30]
Hello,

Can we eager load on the like and dislike count?
I display these two count on each comment. So for 50 comments it makes 100 queries of this type:
![image](https://user-images.githubusercontent.com/16504272/48381512-7da59f80-e6dc-11e8-86a2-a487a727ce1c.png)

Any way to reduce the queries number of theses counts using eager loader or another trick?

Regards

**Comment by antonkomarev** [comment]
Hello @popouille!
You can try to add `with(['likesCounter', 'dislikesCounter'])` to your eloquent builder.

**Comment by popouille** [comment]
It works Thank you !

**Comment by antonkomarev** [comment]
Thank you for the confirmation!
