### ISSUE TITLE
problem with return the number of posts likes foreach post 

### ISSUE THREAD

**Issue by alimuhnad** [cybercog/laravel-love#31]
hi i am using this plugin and i made 
user table - profile table and posts table 
this is my code 
===========================================>
```php
 public function getfollowsposts()
    {
       $user= Auth::user();
       $a=[];
       $posts = User::find($user->id)->followings;
        foreach ($posts as $value) {
            $post =DB::table('users')
        ->where('users.id','=',$value->id)
        ->leftJoin('posts', 'users.id', '=', 'posts.user_id')
        ->leftJoin('myprofiles', 'users.id', '=', 'myprofiles.user_id')
        ->orderBy('posts.created_at', 'desc')
        ->select('name','myprofiles.user_id','img_post','posts.created_at','posts.id','posts.title','myprofiles.avatar_pic')
        ->get();
            array_push($a,$post);
        }
        return response()->json($a,200);
    }
```
====================================>
how can i get the number of likes for each code coz i tryed every single way and its not working
====================>
```php
  public function postslikesnumber(Request $request){
        $user = Auth::user();   
        $x3= posts::find($request->posts_id)->likesCount;
        return response()->json($x3, 200); 
    }
```
====================>>>>>>
so......
i made function that send request when the function getfollowsposts() loaded put its not good for 
the server requests ....... too many requests 
so any help ??? i ll be thankfull

**Comment by alimuhnad** [comment]
how can i do it with  Eloquent to fetch all this data --------------- i ll try love_like_counters  right now

**Comment by antonkomarev** [comment]
I cannot say how to do it, because it's your application logic, and your models.
Here is [official Eloquent Relationships documentation](https://laravel.com/docs/master/eloquent-relationships)

**Comment by alimuhnad** [comment]
i sow it but no time for read all that ........ i ll read it another item but now the  join love_like_counters table.
worked thanks .....
