### ISSUE TITLE
Getting error when I like a comment

### ISSUE THREAD

**Issue by IIINIII** [cybercog/laravel-love#32]
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'likeable_id' cannot be null (SQL: insert into `love_likes` (`user_id`, `type_id`, `likeable_id`, `likeable_type`, `updated_at`, `created_at`) values (1, LIKE, , App\Comment, 2018-11-24 22:16:35, 2018-11-24 22:16:35))

**Comment by IIINIII** [comment]
Maybe I forgot some configurations. But even if I did please help.

**Comment by antonkomarev** [comment]
Hi, @IIINIII 
That seems really strange because `likeable_type` equal to `App\Comment` is in place, but there is no `likeable_id` value.
Could you show how exactly are you trying to like `App\Comment` model? And code of the `App\Comment` model may be required to dive deeper.

**Comment by antonkomarev** [comment]
Did you overwrite `getKey()` method in `App\Comment` model? It could be an issue with it.

**Comment by IIINIII** [comment]
And the method performing likes looks like this:
```php
public function toggleLike(Comment $comment)
    {
        $comment->toggleLikeBy();

        return redirect()->back();
    }
```

**Comment by antonkomarev** [comment]
Your `Likeable` model code seems OK.

Are you sure that `$comment` model is persisted in database? Because possibly you are passing not persisted model which don't have unique identifier yet.

For example this code will have same issue:
```php
$comment = new Comment();
$comment->toggleLikeBy();
```

**Comment by IIINIII** [comment]
Ok I guess I found the problem. It is because my toggleLike function was not able to convert id to my Comment model.

**Comment by IIINIII** [comment]
Thank you anyway :)

**Comment by antonkomarev** [comment]
You are welcome! Glad you found an answer, and thank you for posting the solution.
