### ISSUE TITLE
Return value of LikeableService::getLikerUserId() must be of the type integer

### ISSUE THREAD

**Issue by jaswindersinghnarula** [cybercog/laravel-love#38]
Hi,

I am receiving following error while calling `$me->toggleLike($media)` . Where `$me` is `User `model and `$media` is `Media `model of `MediaLibrary`  .

`Symfony\Component\Debug\Exception\FatalThrowableError: Return value of Cog\Laravel\Love\Likeable\Services\LikeableService::getLikerUserId() must be of the type integer, object returned in file C:\Work\Website\ModelsWay.com\bin\vendor\cybercog\laravel-love\src\Likeable\Services\LikeableService.php on line 369`

Please help me resolve this issue. I can paste whole stack trace if you want.

Regards,

**Comment by antonkomarev** [comment]
If this method returns some kind of object which represents user id - you can overwrite service class with your own implementation and re-bind it in your `AppServiceProvider`:
```php
$this->app->singleton(
    \Cog\Contracts\Love\Likeable\Services\LikeableService::class,
    YourCustomLikeableService::class
);
```

**Comment by jaswindersinghnarula** [comment]
Hi @antonkomarev , After lot of code searching and banging my head on my desk couple of times. I found out that I was missing implementation of `LikerContract` on my User model. In other words I'm a dummy. Anyways thanks for your reply. You can close this issue.

**Comment by antonkomarev** [comment]
Thank you for sharing the solution.
