### ISSUE TITLE
$user->getReacter() or $user->getLoveReacter() ?

### ISSUE THREAD

**Issue by affektde** [cybercog/laravel-love#46]
In README it's `$user->getReacter()`
but I think you mean `$user->getLoveReacter()` is that right?

```
#### Get reacter model

Only `Reacter` model can react to content. Get `Reacter` model from your `Reacterable` model. 

```php
$reacter = $user->getReacter();
```

**Comment by antonkomarev** [comment]
@affektde thanks for pointing that out! You are right, it should be `$user->getLoveReacter()`.
Fixed in last commit.

This prefixes were added after I found that some different packages could have same model names, but behave differently, and documentation was outdated.
