### ISSUE TITLE
Refactor API from v5 to v6

### ISSUE THREAD

**Issue by antonkomarev** [cybercog/laravel-love#5]
The main goal of this refactoring is start to use strict types where it is possible and refactor relationships.

Right now API v5 has issue with methods naming because `Likeable` model cannot act as `Liker` model in the same time. This could be useful when `User` can like `User`.

**Comment by a-komarev** [comment]
#### (?) LikeableService contract

##### Old

```php
public function addLikeTo(Likeable $likeable, $type, $userId);
public function removeLikeFrom(Likeable $likeable, $type, $userId);
public function toggleLikeOf(Likeable $likeable, $type, $userId);
public function isLiked(Likeable $likeable, $type, $userId): bool;
```

##### New

Change methods argument order in `LikeableService` contract and accept only strict types.

```php
public function addLikeTo(Likeable $likeable, Liker $user, LikeType $type);
public function removeLikeFrom(Likeable $likeable, Liker $user, LikeType $type);
public function toggleLikeOf(Likeable $likeable, Liker $user, LikeType $type);
public function isLiked(Likeable $likeable, Liker $user, LikeType $type): bool;
```

**Comment by a-komarev** [comment]
#### (?) Strict types in Likeable model methods

It will be good to pass `Liker` model to `Likeable` methods `likeBy`, `dislikeBy`, `isLikedBy`, `isDislikedBy`, `toggleLikeBy`, `toggleDislikeBy`  instead of `user_id`. 

```php
$article->likeBy(Liker $user);
$article->dislikeBy(Liker $user);

$article->isLikedBy(Liker $user);
$article->isDislikedBy(Liker $user);

$article->toggleLikeBy(Liker $user);
$article->toggleDislikeBy(Liker $user);
```

**Comment by a-komarev** [comment]
#### (?) Assert likes by current user

##### Old

```php
$article->liked;
$article->liked();
$article->disliked;
$article->disliked();
```

##### New

We should throw ability to check likes by current user or we could add new method if needed:

```php
$article->isLikedByMe();
$article->isDislikedByMe();
```

**Comment by a-komarev** [comment]
#### (?) Magical attributes

Magical calls of the attributes `$article->liked` & `$article->disliked` could be dropped. Since it only Laravel related and doesn't give any benefits.

**Comment by a-komarev** [comment]
### Relationships

#### Old implementation

Relationships exists only in `Likeable` model now:

```php
// Likes and dislikes related to Likeable
$likesAndDislikes = $article->likesAndDislikes();

// Likes related to Likeable
$likes = $article->likes();

// Dislikes related to Likeable
$dislikes = $article->dislikes();
```

#### New implementation

Under discussion in #7.

**Comment by antonkomarev** [comment]
Closing this issue since its outdated. I've completely revised an API of the next package version.
More details about v6: #15
