### ISSUE TITLE
Reacter is invalid

### ISSUE THREAD

**Issue by Markwes** [cybercog/laravel-love#50]
Hey there, just tried using your package but I can't seem to get it working.

I want to create a simple like functionality so I followed the instructions in the documentation, but it tells me the reacter is invalid.

I get this error when I try to like/dislike:
`message: "Reacter not exists.", exception: "Cog\Contracts\Love\Reacter\Exceptions\ReacterInvalid",…}
exception: "Cog\Contracts\Love\Reacter\Exceptions\ReacterInvalid"
file: "D:\xampp\htdocs\readclub\vendor\cybercog\laravel-love\contracts\Reacter\Exceptions\ReacterInvalid.php"
line: 24
message: "Reacter not exists."`

This is my code:
`namespace App\Http\Controllers;

```php
use Illuminate\Http\Request;
use Cog\Laravel\Love\ReactionType\Models\ReactionType;
use App\Prompt;
use Auth;
use Session;

class LikeController extends Controller
{
  public function likePrompt(Request $request, $slug) {
    $prompt = Prompt::where('slug', $slug)->first();
    $user = Auth::user();
    $reacter = $user->getLoveReacter();
    $reactant = $prompt->getLoveReactant();
    $likeType = ReactionType::fromName('Like');


    if (!isset($prompt) || !isset($user)) {
      return Response::json(['error' => 'Not a valid prompt or user.'], 404);
    }

    if ($reacter->isReactedTo($reactant)) {
      // Already reacted to prompt
      // Remove like from prompt
      $reacter->unreactTo($reactant, $likeType);
    } else {
      // Not reacted to prompt
      // Add like to prompt
      $reacter->reactTo($reactant, $likeType);
    }

    return Response::json(['success' => true]);

  }
}
```

When I debug $reacter and $reactant it tells me I have the NullReacter and NullReactent, but when I run the function $user->isRegisteredAsLoveReacter() and $prompt->isRegisteredAsLoveReactant() they both return true, so they should be registered.

**Comment by antonkomarev** [comment]
Could you try to register it, please? Will it throw an exception that it's already registered?

**Comment by antonkomarev** [comment]
Closing it because there is no additional information provided. Feel free to continue conversation if issue still exists.

**Comment by emir** [comment]
Same here. In my implementation I solved that problem with checking Exception rather than **isReactedTo()**:

```php
try {
    $reacterFacade->reactTo($model, 'Like');
} catch (ReactionAlreadyExists $exception) {
    return response()->json([], 400);
}
```

**Comment by antonkomarev** [comment]
Your solution is right @emir! 
Laravel Love follows `Tell-Don't-Ask` principle. Rather than asking an object for data and acting on that data, we should instead tell an object what to do.

In case of fail there will be one of the exceptions thrown.
In case of success action will be executed silently and result will be received as background events.
