### ISSUE TITLE
reactTo Method

### ISSUE THREAD

**Issue by marbellacovino** [cybercog/laravel-love#52]
Is it the reactTo() included in the following trait?
use Cog\Laravel\Love\Reactable\Models\Traits\Reactable;

My model Post which is using the Reactable trait cannot find the reactTo method...I am getting the following error: "Call to undefined method App\Post::reactTo()"

How can I fix it?

**Comment by antonkomarev** [comment]
Hi, @marbellacovino!

You are right, `Post` model should be `Reactable`. But only `Reacterable` model has `reactTo` method.
Usually `User` is `Reacterable`.

**Comment by marbellacovino** [comment]
Great thx, I will try that...Is it ReactionType a model I should create on my project?

**Comment by antonkomarev** [comment]
Yeah. It's a model and you can create them using console command described here: https://github.com/cybercog/laravel-love/pull/51

**Comment by antonkomarev** [comment]
I'm closing this issue. Feel free to continue conversation here if there are still unresolved questions.
