### ISSUE TITLE
[Feature Request] add configuration file and allow to specify database connection

### ISSUE THREAD

**Issue by vesper8** [cybercog/laravel-love#61]
I know I had already opened #27 about this and you mention how to workaround it by creating your own models and creating bindings

however now that you have added even more models, it seems like a very tedious solution to have to create duplicate models, extend them and then bind them in your service provider

a much more practical approach would be to allow us to publish a configuration file where we could specify the database connection for all the migrations and models. I really appreciate packages that include this allowance as I use multi-database schemes in many of my larger projects

this is a minor change that would allow full backwards compatibility including for those who don't publish the file since it would have sensible defaults

I recently created a PR for another package that added this very same thing, you can look at it here. If you want I could create a PR for your package too

https://github.com/laravel-notification-channels/webpush/pull/85

Thanks for considering this!

**Comment by antonkomarev** [comment]
It's good idea to have configurable connection. The only thing I don't like - usage of `config()` helper method inside of the package models. I'd prefer to resolve it out from Container inside Service Provider and share with models somehow. I'm ready to dive into it after finishing v6.3

**Comment by antonkomarev** [comment]
@vesper8 first mockup implemented in PR #68 
I need to take a break and think about it a bit more. I hope it will go live pretty soon.

**Comment by vesper8** [comment]
thanks a lot for working on this @antonkomarev !

I had a look at the PR and it looks good. I have to say though I'm not sure if using constants to avoid using the config helper is justified. I haven't seen the use of constants in such a long time personally, I thought it was considered bad practice from a previous era of PHP.

Also, whenever I want to see what are 'best practices' as far as doing anything, I like to use official Laravel packages as the gold standard.

You can see here how Laravel Telescope handles allowing the user to set a connection name:

https://github.com/laravel/telescope/blob/2.0/config/telescope.php
https://github.com/laravel/telescope/blob/2.0/src/Storage/migrations/2018_08_08_100000_create_telescope_entries_table.php
https://github.com/laravel/telescope/blob/2.0/src/TelescopeServiceProvider.php#L154-L156

Also, it uses a single migration file for multiple tables which I think makes sense in the context of a package. Less code duplication that way and no need to extend your own migration file.

Some food for thought : ) Of course your way will also work fine.

Cheers!

**Comment by antonkomarev** [comment]
@vesper8 is there is a need to change connection in runtime?

Because if we will use constant - it could be defined only once on application bootstrapping and it's immutable.

**Comment by antonkomarev** [comment]
This feature has been released in [v7.1](https://github.com/cybercog/laravel-love/releases/tag/7.1.0)
