### ISSUE TITLE
[Concept] Mutually exclusive reactions

### ISSUE THREAD

**Issue by antonkomarev** [cybercog/laravel-love#75]
To implement functionality like Reddit Votes and YouTube Likes we need to introduce mutually exclusive reactions.

Without it Reacter could react to Reactant with `like` and `dislike` simultaneously.

This is non-strict requirement because same behavior could be implemented in controller on application-level.

```php
$reacter = $user->viaLoveReacter();

if ($reacter->hasReactedTo($comment, 'Dislike')) {
    $reacter->unreactTo($comment, 'Dislike');
}

$reacter->reactTo($comment, 'Like');
```

### Things to consider

- Not all parts of the application should have same behavior. Post & comments could require mutually exclusive reactions, but instant messenger messages wouldn't need it.
- Need to take into account new Weighted Reaction System #85

### In closing

If there is something I'm missing in "Things to consider" or there is other way to solve this issue? Your suggestions are welcome!

**Comment by antonkomarev** [comment]
### Solution №1

Add boolean flag to configuration `is_mutually_exclusive`.

#### Pros

- Easy to implement.

#### Cons

- Require to publish config to change boolean flag. It might be an issue because this feature is required pretty frequently.

**Comment by antonkomarev** [comment]
### Solution №2

Add special method for mutually exclusive reactions.

```php
$reacter = $user->viaLoveReacter();

$reacter->exclusiveReactTo($comment, 'Like');
```

#### Pros

- Easy to use out of the box.

#### Cons

- Bloats API.

**Comment by antonkomarev** [comment]
[WIP] Solution №3

Introduce special service classes which will encapsulate different reaction logic for the most comon use cases out from the controllers and will throw custom exceptions for the each unexpected case.

- `ReactOnlyOnceService`

**Comment by antonkomarev** [comment]
### [WIP] Solution №4

Introduce special service class which will receive different reaction rules which will be executed on reaction/unreaction.

```php
$reactionRules = [
    NonUnreactableReactionRule::class,
];
$service = new ReactionService($reactionRules, $user);
$service->reactTo($article, 'like', $rate);
$service>unreactTo($article, 'like');
// throws `UnreactionNotAllowed` exception
```

Mutually exclusive reactions:
```php
$reactionRules = [
    OverwritableReactionRule::class,
];
$service = new ReactionService($reactionRules, $user);
$service->reactTo($article, 'like', $rate);
$service->reactTo($article, 'dislike', $rate);
// removes `like` reaction and adds `dislike` reaction
```

Mututally exclusive reactions which will throw an exception if another one is exists:
```php
$reactionRules = [
    MutuallyExclusiveReactionRule::class,
];
$service = new ReactionService($reactionRules, $user);
$service->reactTo($article, 'like', $rate);
$service->reactTo($article, 'dislike', $rate);
// throws `MutuallyExclusiveReactionViolation` exception
```

#### Pros

- ?

#### Cons

- ?

**Comment by antonkomarev** [comment]
### [WIP] Solution №5

Introduce special service class which will receive different reaction rules sets for each model type. They will be executed on reaction/unreaction depending on the provided model.

```php
$reactionRules = [
    \App\ArticleModel::class => [
        NonUnreactableReactionRule::class,
    ],
];
$service = new ReactionService($reactionRules, $user);
$service->reactTo($article, 'like', $rate);
$service->unreactTo($article, 'like');
// throws `UnreactionNotAllowed` exception
```

Mutually exclusive reactions:
```php
$reactionRules = [
    \App\ArticleModel::class => [
        OverwritableReactionRule::class,
    ],
];
$service = new ReactionService($reactionRules, $user);
$service->reactTo($article, 'like', $rate);
$service->reactTo($article, 'dislike', $rate);
// removes `like` reaction and adds `dislike` reaction
```

Mututally exclusive reactions which will throw an exception if another one is exists:
```php
$reactionRules = [
    \App\ArticleModel::class => [
        MutuallyExclusiveReactionRule::class,
    ],
];
$service = new ReactionService($reactionRules, $user);
$service->reactTo($article, 'like', $rate);
$service->reactTo($article, 'dislike', $rate);
// throws `MutuallyExclusiveReactionViolation` exception
```

#### Pros

- ?

#### Cons

- ?

**Comment by jayenne** [comment]
Did you get anywhere on this Anton?

I would be in favor of an 'exclusive-reaction' implementation on per model basis.

I would also think that a model (even exclusive-reaction models) should have a max limit of reactions such as medium's claps cap.

I know both systems could be managed via the ui & controller but for simplicity adding it to the package would be a simpler means to implement it.

**Comment by antonkomarev** [comment]
@jayenne Not yet. I'm still on stage of researching all possible ways of implementation. As you noted - it is easy to implement in your own application, so I'm not rushing to introduce this feature. I weigh all the pros and cons and try to anticipate how this will affect further development.

Thanks for mentioning max limit of reactions. That's looks like reaction rule too.

**Comment by antonkomarev** [comment]
### [WIP] Solution №6

Introduce special service class which will receive different reaction rules sets for each model type. They will be executed on reaction/unreaction depending on the provided model. User model should be passed into the `react/unreact` methods to be able to resolve service class out from the container.

```php
$this->app->singleton(ReactionService::class, function () {
    $reactionRules = [
        ArticleModel::class => [
            NonUnreactableReactionRule::class,
        ],
    ];

    return new ReactionService($reactionRules);
});

$service = app(ReactionService::class);
$service->react($user, 'like', $article, $rate);
$service->unreact($user, 'like', $article);
// throws `UnreactionNotAllowed` exception
```

Mutually exclusive reactions:
```php
$this->app->singleton(ReactionService::class, function () {
    $reactionRules = [
        ArticleModel::class => [
            OverwritableReactionRule::class,
        ],
    ];

    return new ReactionService($reactionRules);
});

$service = app(ReactionService::class);
$service->react($user, 'like', $article, $rate);
$service->react($user, 'dislike', $article, $rate);
// removes `like` reaction and adds `dislike` reaction
```

Mututally exclusive reactions which will throw an exception if another one is exists:
```php
$this->app->singleton(ReactionService::class, function () {
    $reactionRules = [
        ArticleModel::class => [
            MutuallyExclusiveReactionRule::class,
        ],
    ];

    return new ReactionService($reactionRules);
});

$service = app(ReactionService::class);
$service->react($user, 'like', $article, $rate);
$service->unreact($user, 'dislike', $article, $rate);
// throws `MutuallyExclusiveReactionViolation` exception
```

#### Pros

- ?

#### Cons

- ?

**Comment by antonkomarev** [comment]
### [WIP] Solution №7

Use decorator design pattern.

```php
$reacter = $user->getLoveReacter();
$reactant = $article->getLoveReactant();
$reactonType = ReactionType::fromName('Like');
$reaction = new NonUnreactableReaction(
    new Reaction($reacter, $reactant, $reactionType, $rate)
);

$reaction->react();
$reaction->unreact();
// throws `UnreactionNotAllowed` exception
```

Mutually exclusive reactions:
```php
$reacter = $user->getLoveReacter();
$reactant = $article->getLoveReactant();
$likeReactonType = ReactionType::fromName('Like');
$likeReaction = new OverwritableReaction(
    new Reaction($reacter, $reactant, $reactionType, $rate)
);

$likeReaction->react();

$dislikeReactonType = ReactionType::fromName('Dislike');
$dislikeReaction = new OverwritableReaction(
    new Reaction($reacter, $reactant, $reactionType, $rate)
);

$dislikeReaction->react();
// removes `Like` reaction and adds `Dislike` reaction
```

Mututally exclusive reactions which will throw an exception if another one is exists:
```php
$reacter = $user->getLoveReacter();
$reactant = $article->getLoveReactant();
$likeReactonType = ReactionType::fromName('Like');
$likeReaction = new MutuallyExclusiveReaction(
    new Reaction($reacter, $reactant, $reactionType, $rate)
);

$likeReaction->react();

$dislikeReactonType = ReactionType::fromName('Dislike');
$dislikeReaction = new MutuallyExclusiveReaction(
    new Reaction($reacter, $reactant, $reactionType, $rate)
);

$dislikeReaction->react();
// throws `MutuallyExclusiveReactionViolation` exception
```

#### Pros

- ?

#### Cons

- ?
